config/routes.rb
Joga::Application.routes.draw do

  post "*all" => "application#cors_preflight_check", :constraints => { :method => "OPTIONS" }
  devise_for :users, 
  :controllers => { 
    :registrations => "registrations",
    :sessions => "sessions",
    :omniauth_callbacks => "users/omniauth_callbacks"
    }, 
  :path_names => { 
    :sign_in => 'login', 
    :sign_out => 'logout',
    :password => 'secret', 
    :confirmation => 'verification', 
    registration: 'register' }, 
  :token_authentication_key => 'authentication_key' 

  devise_scope :user do
      resources :user_settings
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_facebook

  end

  post 'matches' => 'matches#all'
  post 'stadia' => 'stadia#all'
  post 'teams' => 'teams#all'

  
  post 'leagues/create' => 'leagues#create'
  post 'leagues/update' => 'leagues#update'
  post 'league' => 'leagues#show'
  post 'leagues/mainleague' => 'leagues#main_league'
  post 'leagues/globalstanding' => 'leagues#main_league_me'
  post 'leagues/leaguestanding' => 'leagues#league_me'
  post 'leagues/respondinvitation' => 'leagues#respond_invitation'
  post 'leagues/pendinginvitations' => 'leagues#pending_league_invitations'

  post 'leagues/invite' => 'leagues#invite_users'
  post 'leagues/comments' => 'comments#viewAll'
  post 'leagues/comments/add' => 'comments#create'
  post 'leagues/comments/remove' => 'comments#destroy'
  post 'leagues/comments/like' => 'comments#like'
  post 'leagues/comments/unlike' => 'comments#unlike'

  
  post 'predictions/create' => 'prediction#create'
  post 'predictions' => 'prediction#viewAllCurrentUser'
  post 'predictions/updatePoints' => 'prediction#updatePoints'
  post 'predictions/friendpredictions' => 'prediction#predictions'
  post 'predictions/update' => 'prediction#update'
  post 'user/me' => 'user_settings#me'
  post 'user/friend' => 'user_settings#friend_profile'
  
  post 'league/friendleagues' => 'leagues#leagues'
  post 'league/myleagues' => 'leagues#my_leagues'

  post 'users/check' => 'user#check_user_presence'
  post 'users/forgotpass'  => 'user#request_password_reset'
  post 'users/resetpass'  => 'user#change_password'

  get '*a' => 'application#render_404'

  

end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController
  before_action :set_stadium, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user_from_token!, :only => [ :all ]
  skip_before_filter :authenticate_user!, :only => [:all]

  # GET /stadia
  def index
    @stadia = Stadium.all
  end

  # post /stadia
  def all
    render json: Stadium.all.to_json, status: :ok
  end
  # GET /stadia/1
  def show
  end

  # GET /stadia/new
  def new
    @stadium = Stadium.new
  end

  # GET /stadia/1/edit
  def edit
  end

  # POST /stadia
  def create
    @stadium = Stadium.new(stadium_params)

    if @stadium.save
      redirect_to @stadium, notice: 'Stadium was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /stadia/1
  def update
    if @stadium.update(stadium_params)
      redirect_to @stadium, notice: 'Stadium was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /stadia/1
  def destroy
    @stadium.destroy
    redirect_to stadia_url, notice: 'Stadium was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stadium
      @stadium = Stadium.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stadium_params
      params[:stadium]
    end
end

app/views/stadia/_form.html.erb
<%= form_for(@stadium) do |f| %>
  <% if @stadium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stadium.errors.count, "error") %> prohibited this stadium from being saved:</h2>

      <ul>
      <% @stadium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stadia/edit.html.erb
<h1>Editing stadium</h1>

<%= render 'form' %>

<%= link_to 'Show', @stadium %> |
<%= link_to 'Back', stadia_path %>

app/views/stadia/index.html.erb
<h1>Listing stadia</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stadia.each do |stadium| %>
      <tr>
        <td><%= stadium.name %></td>
        <td><%= stadium.city %></td>
        <td><%= link_to 'Show', stadium %></td>
        <td><%= link_to 'Edit', edit_stadium_path(stadium) %></td>
        <td><%= link_to 'Destroy', stadium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stadium', new_stadium_path %>

app/views/stadia/new.html.erb
<h1>New stadium</h1>

<%= render 'form' %>

<%= link_to 'Back', stadia_path %>

app/views/stadia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stadium.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @stadium.city %>
</p>

<%= link_to 'Edit', edit_stadium_path(@stadium) %> |
<%= link_to 'Back', stadia_path %>